import { useState, useEffect } from 'react';
import { safeGet } from "@api/api.js";
export default function Admin(){const [msg,setMsg]=useState('');const [spec,setSpec]=useState({name:'',icon:''});const [clinic,setClinic]=useState({name:'',address:'',tags:'',stars:4.5});const [post,setPost]=useState({title:'',excerpt:'',tag:'',reading:''});const [specialties,setSpecialties]=useState([]);const [clinics,setClinics]=useState([]);const [posts,setPosts]=useState([]);
const login=async()=>{const r=await API.post('/auth/login',{email:'admin@bookcare.vn',password:'password'});localStorage.setItem('token',r.data.token);setMsg('Đăng nhập admin OK');};
const refresh=async()=>{const s=await API.get('/specialties');setSpecialties(s.data);const c=await API.get('/clinics');setClinics(c.data);const p=await API.get('/posts');setPosts(p.data);};
useEffect(()=>{refresh();},[]);
const submitSpec=async(e)=>{e.preventDefault();await API.post('/specialties',spec);setSpec({name:'',icon:''});setMsg('Đã thêm chuyên khoa');refresh();};
const submitClinic=async(e)=>{e.preventDefault();await API.post('/clinics',clinic);setClinic({name:'',address:'',tags:'',stars:4.5});setMsg('Đã thêm cơ sở y tế');refresh();};
const submitPost=async(e)=>{e.preventDefault();await API.post('/posts',post);setPost({title:'',excerpt:'',tag:'',reading:''});setMsg('Đã thêm bài viết');refresh();};
return(<div style={{padding:20,maxWidth:900,margin:'0 auto'}}><h2>Admin nhập dữ liệu</h2><p style={{color:'green'}}>{msg}</p><button onClick={login}>Đăng nhập nhanh (admin/password)</button><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:16}}><form onSubmit={submitSpec} style={{border:'1px solid #eee',padding:12,borderRadius:8}}><h4>Thêm Chuyên khoa</h4><input placeholder='Tên' value={spec.name} onChange={e=>setSpec({...spec,name:e.target.value})}/><br/><input placeholder='Icon' value={spec.icon} onChange={e=>setSpec({...spec,icon:e.target.value})}/><br/><button type='submit'>Thêm</button><ul>{specialties.map(s=><li key={s.id}>{s.icon} {s.name}</li>)}</ul></form><form onSubmit={submitClinic} style={{border:'1px solid #eee',padding:12,borderRadius:8}}><h4>Thêm Cơ sở y tế</h4><input placeholder='Tên' value={clinic.name} onChange={e=>setClinic({...clinic,name:e.target.value})}/><br/><input placeholder='Địa chỉ' value={clinic.address} onChange={e=>setClinic({...clinic,address:e.target.value})}/><br/><input placeholder='Tags (phẩy ,)' value={clinic.tags} onChange={e=>setClinic({...clinic,tags:e.target.value})}/><br/><input placeholder='Stars' type='number' step='0.1' value={clinic.stars} onChange={e=>setClinic({...clinic,stars:parseFloat(e.target.value)})}/><br/><button type='submit'>Thêm</button><ul>{clinics.map(c=><li key={c.id}>{c.name} - {c.address}</li>)}</ul></form></div><form onSubmit={submitPost} style={{border:'1px solid #eee',padding:12,borderRadius:8,marginTop:16}}><h4>Thêm Bài viết</h4><input placeholder='Tiêu đề' value={post.title} onChange={e=>setPost({...post,title:e.target.value})}/><br/><input placeholder='Excerpt' value={post.excerpt} onChange={e=>setPost({...post,excerpt:e.target.value})}/><br/><input placeholder='Tag' value={post.tag} onChange={e=>setPost({...post,tag:e.target.value})}/><br/><input placeholder='Thời gian đọc' value={post.reading} onChange={e=>setPost({...post,reading:e.target.value})}/><br/><button type='submit'>Thêm</button><ul>{posts.map(p=><li key={p.id}>{p.title} - {p.tag}</li>)}</ul></form></div>);}
